/*
  Warnings:

  - The `occupation` column on the `User` table would be dropped and recreated. This will lead to data loss if there is data in the column.

*/
-- CreateEnum
CREATE TYPE "Occupation" AS ENUM ('PHYSICIAN', 'NURSE', 'DENTIST', 'PHARMACIST', 'PHYSICAL_THERAPIST', 'SOFTWARE_ENGINEER', 'DATA_SCIENTIST', 'SYSTEM_ADMINISTRATOR', 'NETWORK_ENGINEER', 'UX_DESIGNER', 'TEACHER', 'PROFESSOR', 'EDUCATIONAL_CONSULTANT', 'LIBRARIAN', 'SCHOOL_ADMINISTRATOR', 'ACCOUNTANT', 'FINANCIAL_ANALYST', 'BUSINESS_CONSULTANT', 'MARKETING_MANAGER', 'HUMAN_RESOURCES_MANAGER', 'LAWYER', 'PARALEGAL', 'LEGAL_CONSULTANT', 'JUDGE', 'GRAPHIC_DESIGNER', 'WRITER', 'JOURNALIST', 'PHOTOGRAPHER', 'ARTIST', 'ELECTRICIAN', 'PLUMBER', 'CARPENTER', 'CONSTRUCTION_MANAGER', 'MECHANIC', 'CHEF', 'HOSPITALITY_MANAGER', 'RETAIL_MANAGER', 'CUSTOMER_SERVICE_REPRESENTATIVE', 'SALES_REPRESENTATIVE', 'SCIENTIST', 'RESEARCHER', 'LABORATORY_TECHNICIAN', 'ENVIRONMENTAL_SCIENTIST', 'POLICE_OFFICER', 'FIREFIGHTER', 'SOCIAL_WORKER', 'URBAN_PLANNER', 'PUBLIC_ADMINISTRATOR', 'PILOT', 'TRUCK_DRIVER', 'LOGISTICS_COORDINATOR', 'SHIP_CAPTAIN', 'FARMER', 'AGRICULTURAL_CONSULTANT', 'VETERINARIAN', 'SELF_EMPLOYED', 'RETIRED', 'STUDENT', 'OTHER');

-- AlterTable
ALTER TABLE "User" DROP COLUMN "occupation",
ADD COLUMN     "occupation" "Occupation" NOT NULL DEFAULT 'OTHER';
